(() => {
  'use strict';
  const CFG_KEY='futLiveRealtimeConfigV1';
  const HISTORY_KEY='futLiveHistoryV1';
  const $=s=>document.querySelector(s);
  let socket=null;
  let cfg=loadCfg();
  let history=loadHistory();
  const userSide=new Map();
  function loadCfg(){try{return {...{backendUrl:'',adminPin:'',autoConnect:false},...JSON.parse(localStorage.getItem(CFG_KEY)||'{}')}}catch{return {backendUrl:'',adminPin:'',autoConnect:false}}}
  function saveCfg(){localStorage.setItem(CFG_KEY,JSON.stringify(cfg))}
  function loadHistory(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return []}}
  function saveHistory(){history=history.slice(0,500);localStorage.setItem(HISTORY_KEY,JSON.stringify(history))}
  function addHistory(type,data){history.unshift({time:new Date().toISOString(),type,...data});saveHistory()}
  function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function setStatus(kind,text,detail=''){const dot=$('#connectionDot'),label=$('#connectionText'),sub=$('#connectionDetail');if(dot)dot.className=`connection-dot ${kind}`;if(label)label.textContent=text;if(sub)sub.textContent=detail}
  function effect(icon,title,subtitle=''){const el=$('#eventEffect');if(!el)return;el.innerHTML=`<div><b>${icon}</b><strong>${esc(title)}</strong><small>${esc(subtitle)}</small></div>`;el.classList.remove('show');void el.offsetWidth;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
  function parseSide(comment=''){const n=String(comment).trim().toLowerCase().replace(/\s+/g,'');if(['1','lado1','time1','equipe1'].includes(n))return 1;if(['2','lado2','time2','equipe2'].includes(n))return 2;return 0}
  function receiveComment(data){const username=data.username||data.uniqueId||'usuário';const comment=data.comment||'';const side=parseSide(comment);if(side){userSide.set(username,side);effect('⚔️',`${username} escolheu`,`Lado ${side}`)}addHistory('comment',{username,comment,side})}
  function receiveGift(data){const username=data.username||data.uniqueId||'usuário';const giftName=data.giftName||data.name||'Presente';const side=userSide.get(username);const points=Math.max(1,Number(data.diamondCount||1))*Math.max(1,Number(data.repeatCount||1));if(!side){effect('⚠️',`${username} enviou presente`,'Comente 1 ou 2 antes para escolher um lado');addHistory('gift',{username,giftName,points,side:0});return}window.FutLiveBattle?.receiveGift({side,points,username,giftName});addHistory('gift',{username,giftName,points,side});effect('🎁',`${username} pontuou`,`Lado ${side} · +${points}`)}
  function receiveLike(data){const username=data.username||data.uniqueId||'usuário';const count=Math.max(1,Number(data.likeCount||data.count||1));window.FutLivePanel?.receiveLike(username,count);addHistory('like',{username,count})}
  function receiveFollow(data){const username=data.username||data.uniqueId||'usuário';window.FutLivePanel?.receiveFollow(username);addHistory('follow',{username});effect('➕','NOVO SEGUIDOR',username)}
  function bindSocket(s){s.on('connect',()=>setStatus('online','Backend conectado','Aguardando conexão com a LIVE'));s.on('disconnect',()=>setStatus('offline','Backend desconectado','Reconectando automaticamente…'));s.on('connect_error',e=>setStatus('error','Erro no backend',e.message));s.on('tiktok:status',d=>setStatus(d.connected?'live':'online',d.connected?'LIVE conectada':'Backend conectado',d.message||d.username||''));s.on('tiktok:comment',receiveComment);s.on('tiktok:gift',receiveGift);s.on('tiktok:like',receiveLike);s.on('tiktok:follow',receiveFollow);s.on('tiktok:roomUser',d=>{const el=$('#viewerCount');if(el)el.textContent=new Intl.NumberFormat('pt-BR',{notation:'compact'}).format(d.viewerCount||0)});s.on('tiktok:error',d=>{setStatus('error','Erro na LIVE',d.message||'Falha desconhecida');effect('⚠️','ERRO NA CONEXÃO',d.message||'')})}
  function connectBackend(){const url=cfg.backendUrl.trim().replace(/\/$/,'');if(!url||typeof io!=='function'){setStatus('error','Backend não configurado','Abra Conectar LIVE');return}socket?.disconnect();setStatus('loading','Conectando backend',url);socket=io(url,{transports:['websocket','polling'],reconnection:true,reconnectionDelay:1500,auth:{pin:cfg.adminPin}});bindSocket(socket)}
  function connectTikTok(username){if(!socket?.connected)return alert('Conecte primeiro ao backend.');const clean=String(username||'').replace(/^@/,'').trim();if(!clean)return alert('Digite o @ da conta.');socket.emit('tiktok:connect',{username:clean,pin:cfg.adminPin},reply=>{if(reply?.ok)setStatus('loading','Conectando à LIVE',`@${clean}`);else alert(reply?.error||'Não foi possível conectar')})}
  function openConnection(){window.openModal?.(`<h3>Conectar TikTok LIVE</h3><label>URL do backend<input id="rtBackend" class="modal-input" value="${esc(cfg.backendUrl)}" placeholder="https://seu-backend.onrender.com"></label><label>PIN do administrador<input id="rtPin" class="modal-input" type="password" value="${esc(cfg.adminPin)}"></label><label>Usuário TikTok<input id="rtUser" class="modal-input" placeholder="@usuario"></label><label class="check-line"><input id="rtAuto" type="checkbox" ${cfg.autoConnect?'checked':''}> Reconectar automaticamente</label><button id="rtSave" class="modal-action">Salvar e conectar</button><p class="helper-text">Na LIVE, cada pessoa comenta 1 ou 2 para escolher um lado antes de enviar o presente.</p>`);$('#rtSave').onclick=()=>{cfg.backendUrl=$('#rtBackend').value.trim();cfg.adminPin=$('#rtPin').value.trim();cfg.autoConnect=$('#rtAuto').checked;saveCfg();const user=$('#rtUser').value.trim();window.closeModal?.();connectBackend();setTimeout(()=>connectTikTok(user),1200)}}
  function openHistory(){const gifts=history.filter(x=>x.type==='gift'&&x.side);const s1=gifts.filter(x=>x.side===1).reduce((a,b)=>a+(Number(b.points)||0),0);const s2=gifts.filter(x=>x.side===2).reduce((a,b)=>a+(Number(b.points)||0),0);window.openModal?.(`<h3>Histórico da batalha</h3><div class="history-summary"><div><b>${s1}</b><small>Lado 1</small></div><div><b>${s2}</b><small>Lado 2</small></div><div><b>${gifts.length}</b><small>presentes</small></div></div><div class="modal-list">${history.slice(0,30).map(e=>`<div class="modal-item"><strong>${esc(e.username||e.type)}</strong><small>${e.type==='gift'?`Lado ${e.side||'-'} · +${e.points||0}`:esc(e.comment||e.type)}</small></div>`).join('')||'<p>Nenhum evento.</p>'}</div><button id="clearHistory" class="modal-danger">Limpar histórico</button>`);$('#clearHistory').onclick=()=>{if(confirm('Apagar o histórico?')){history=[];saveHistory();window.closeModal?.()}}}
  $('#connectLiveButton')?.addEventListener('click',openConnection);$('#historyButton')?.addEventListener('click',openHistory);if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});if(cfg.autoConnect&&cfg.backendUrl)connectBackend();window.FutLiveRealtime={connectBackend,connectTikTok,openConnection,openHistory};
})();